import { FeedPost } from "@/components/create-post-dialog";

export const mockPosts: FeedPost[] = [
  {
    _id: "mock-1",
    authorPseudonym: "Stille_Wateren_88",
    type: "GEBED",
    content: "Zouden jullie willen bidden voor mijn vader die herstelt van een zware operatie? We vertrouwen op God voor zijn genezing.",
    upvotes: ["1", "2", "3", "4", "5", "6", "7", "8"],
    scriptureReference: "Psalm 147:3",
    scriptureText: "Hij geneest de gebrokenen van hart, Hij verbindt hun wonden.",
    status: "APPROVED",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "mock-2",
    authorPseudonym: "Dankbare_Pelgrim",
    type: "DANK",
    content: "Vandaag precies een jaar geleden dat ik mijn draai weer vond in de kerk. God is getrouw!",
    upvotes: ["1", "2", "3", "4"],
    status: "APPROVED",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    _id: "mock-3",
    authorPseudonym: "Zoekend_Licht",
    type: "VRAAG",
    content: "Ik heb moeite met het begrijpen van de gelijkenis van de onrechtvaardige rentmeester (Lukas 16). Wie kan dit uitleggen?",
    upvotes: ["1", "3"],
    scriptureReference: "Lukas 16:1-13",
    scriptureText: "Geen huisknecht kan twee heren dienen; want hij zal of de ene haten en de andere liefhebben...",
    status: "APPROVED",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    _id: "mock-4",
    authorPseudonym: "Blijde_Boodschapper",
    type: "DANK",
    content: "Vandaag een diep gesprek gehad met een buurman over het geloof. Hij wil mee naar de dienst!",
    upvotes: ["1", "2", "3", "4", "5", "6"],
    status: "APPROVED",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    _id: "mock-5",
    authorPseudonym: "Vaste_Rots",
    type: "GEBED",
    content: "Ik heb gebed nodig voor volharding in mijn werkplek waar een vijandige sfeer hangt tegenover het christendom.",
    upvotes: ["1", "2", "3"],
    scriptureReference: "2 Timotheüs 1:7",
    scriptureText: "Want God heeft ons niet gegeven een geest van vreesachtigheid, maar van kracht en liefde en bezonnenheid.",
    status: "APPROVED",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];
